# Generated by Django 6.0.3 on 2026-03-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualsection',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
