# Generated by Django 6.0.3 on 2026-03-09 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_manualsection_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('subtitle', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('tag', models.CharField(max_length=50)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.manualsection')),
            ],
            options={
                'ordering': ['version'],
            },
        ),
    ]
