# Generated by Django 6.0.3 on 2026-03-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sectionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
