# Generated by Django 6.0.3 on 2026-03-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_manual_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualsection',
            name='tag',
            field=models.CharField(choices=[('POLICY', 'Policy'), ('PROCEDURE', 'Procedure'), ('RESPONSIBILITY', 'Responsibility'), ('WORKING INSTRUCTION', 'Working Instruction'), ('PAGE_HEADER', 'Page Header'), ('UNTAGGED', 'Untagged')], default='UNTAGGED', max_length=50),
        ),
    ]
