# Generated by Django 6.0.3 on 2026-03-16 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_manualsection_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualsection',
            name='is_reviewed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='manualsection',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualsection',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sections', to=settings.AUTH_USER_MODEL),
        ),
    ]
