# Generated by Django 6.0.3 on 2026-03-16 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_manualsection_is_reviewed_manualsection_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualsection',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.manualsection'),
        ),
    ]
