# Generated by Django 6.0.3 on 2026-03-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_manualsection_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualrevision',
            name='proposed_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='manualrevision',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='revisions/'),
        ),
    ]
