# Generated by Django 6.0.3 on 2026-03-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_manualrevision_proposed_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualrevision',
            name='merge_section_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualrevision',
            name='merge_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
