# Generated by Django 6.0.3 on 2026-03-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_manualrevision_merge_section_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='revision',
            field=models.IntegerField(default=0),
        ),
    ]
