# Generated by Django 6.1 on 2026-09-16 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_manual_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualrevision',
            name='ai_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='manualrevision',
            name='ai_issues',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='manualrevision',
            name='ai_trace',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='manualrevision',
            name='ai_verdict',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='manualrevision',
            name='change_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='manualrevision',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_revisions', to=settings.AUTH_USER_MODEL),
        ),
    ]
