# Generated by Django 6.1 on 2026-09-18 12:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_manualrevision_ai_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualrevision',
            name='ai_advisories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='manualrevision',
            name='ai_assessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualrevision',
            name='ai_change_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='manualrevision',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualrevision',
            name='ai_content_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='manualrevision',
            name='ai_explanation_staff',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='manualrevision',
            name='ai_hard_fails',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='manualrevision',
            name='ai_model_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='manualrevision',
            name='ai_section_content_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='manualrevision',
            name='ai_source',
            field=models.CharField(choices=[('staff_precheck', 'Checked by the submitter before submitting'), ('admin_legacy', 'Assessed by the reviewer under the previous workflow'), ('none', 'Not assessed')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='RevisionPreAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('section_content_hash', models.CharField(max_length=64)),
                ('proposed_content', models.TextField(blank=True)),
                ('change_reason', models.TextField(blank=True)),
                ('verdict', models.CharField(blank=True, max_length=32)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('change_type', models.CharField(blank=True, max_length=40)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('hard_fails', models.JSONField(blank=True, default=list)),
                ('advisories', models.JSONField(blank=True, default=list)),
                ('explanation_reviewer', models.TextField(blank=True)),
                ('explanation_staff', models.TextField(blank=True)),
                ('trace', models.JSONField(blank=True, default=dict)),
                ('model_fingerprint', models.CharField(blank=True, max_length=64)),
                ('pipeline_version', models.CharField(blank=True, max_length=8)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_assessment', to='api.manualrevision')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_assessments', to='api.manualsection')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assessed_at'],
                'indexes': [models.Index(fields=['submitted_by', 'section', 'content_hash'], name='api_revisio_submitt_92603d_idx')],
            },
        ),
    ]
