# Generated by Django 6.1 on 2026-09-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_backfill_ai_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualrevision',
            name='feedback_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
