# Generated by Django 6.0.1 on 2026-09-20 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_announcement_announcementdismissal_recentlyopened'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionhistory',
            name='change_reason',
            field=models.TextField(blank=True, help_text="Why this change was made. Carried over from the submitter's reason on an approved revision, typed by the admin on a direct edit."),
        ),
        migrations.AddField(
            model_name='sectionhistory',
            name='revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_versions', to='api.manualrevision'),
        ),
        migrations.AddField(
            model_name='sectionhistory',
            name='source',
            field=models.CharField(choices=[('revision', 'Approved revision'), ('direct', 'Direct edit by an admin'), ('merge', 'Merged with another section'), ('extraction', 'Re-extracted from the master copy'), ('unknown', 'Recorded before edits were attributed')], default='unknown', max_length=20),
        ),
    ]
