# Generated by Django 6.0.1 on 2026-09-22 05:09

import django.db.models.deletion
from django.conf import settings
"""M1 - the organisation tables, additive only.

Creates Office, Position, PositionAssignment and ManualOffice, and adds
the columns the new model needs to CustomUser and Manual. **No existing
column is altered and nothing is deleted**, so reversing this drops the
new tables and columns and leaves v3 exactly as it was.

The tables ship empty. There is no import from the old departments - that
was a decision, not an omission: the system admin enters every office,
manual link and position through screens, so nothing about the
university's structure is written by a script.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_sectionhistory_change_reason_sectionhistory_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='system_role',
            field=models.CharField(choices=[('system_admin', 'System administrator'), ('qms_staff', 'QMS staff'), ('user', 'User')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='manual',
            name='approval_stops_at_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(blank=True, max_length=32)),
                ('is_approving_level', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_from', to='api.office')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='api.office')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='manual',
            name='owning_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_manuals', to='api.office'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('encoder', 'Encoder'), ('head', 'Head'), ('imr', 'Integrated Management Representative'), ('document_custodian', 'Document Custodian')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='api.office')),
            ],
            options={
                'ordering': ['office__name', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='PositionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sole_holder', models.BooleanField(default=False, editable=False)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='api.position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_on', 'position__office__name'],
            },
        ),
        migrations.CreateModel(
            name='ManualOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('concurring', 'Concurring — can propose, must concur'), ('reader', 'Reader — read only, never blocks')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_links', to='api.manual')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_links', to='api.office')),
            ],
            options={
                'ordering': ['manual__title', 'office__name'],
                'constraints': [models.UniqueConstraint(fields=('manual', 'office'), name='one_relationship_per_manual_and_office')],
            },
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('office', 'kind'), name='one_position_row_per_office_and_kind'),
        ),
        migrations.AddConstraint(
            model_name='positionassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ends_on__isnull', True), ('sole_holder', True)), fields=('position',), name='one_current_holder_of_a_sole_holder_position'),
        ),
        migrations.AddConstraint(
            model_name='positionassignment',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='assignment_ends_after_it_starts'),
        ),
    ]
