# Generated by Django 6.0.1 on 2026-09-22 05:09

import django.db.models.deletion
"""Stop the organisation destroying controlled documents.

`Manual.department` cascaded, so removing one Department row deleted every
manual in it, their sections, and every revision ever proposed against
them. `delete_department` was the route that did it; that endpoint is
disabled in the same phase, but the Django admin and the shell reach the
same collector, so the guarantee belongs on the relationship.

`Announcement.department` becomes PROTECT rather than SET_NULL, which
would be actively wrong: null on that field does not mean "no
department", it means **show this to everyone**. Clearing it would
silently broadcast a departmental notice to the whole university.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_map_accounts_to_system_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Leave empty to show this to every department.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='api.department'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manuals', to='api.department'),
        ),
    ]
