# Generated by Django 6.0.1 on 2026-09-22 08:51

import django.db.models.deletion
"""The manual series, and the inheritance that hangs off it.

`approval_stops_at_owner` changes meaning here, which is the part worth
reading twice. In 1a it was `default=False` - two states, and every row
got False. It now allows null, and **null means inherit from the series**.

Left alone, all nineteen existing rows would carry a False that nobody
chose and that would read as "this document explicitly does not follow
its series". So they are set back to null: the field arrived with a
default and no screen to set it, so no row's False was ever a decision.
"""

from django.db import migrations, models


def inherit_approval_route_by_default(apps, schema_editor):
    """Turn the 1a default back into "not decided"."""
    apps.get_model('api', 'Manual').objects.filter(
        approval_stops_at_owner=False
    ).update(approval_stops_at_owner=None)


def explicit_approval_route(apps, schema_editor):
    """Reversing restores the two-state field, where null cannot exist."""
    apps.get_model('api', 'Manual').objects.filter(
        approval_stops_at_owner__isnull=True
    ).update(approval_stops_at_owner=False)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_no_cascade_from_the_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='offices_overridden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='manual',
            name='approval_stops_at_owner',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='ManualSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('approval_stops_at_owner', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owning_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_series', to='api.office')),
            ],
            options={
                'verbose_name_plural': 'manual series',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='manual',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='api.manualseries'),
        ),
        migrations.CreateModel(
            name='ManualSeriesOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('concurring', 'Concurring — can propose, must concur'), ('reader', 'Reader — read only, never blocks')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_links', to='api.office')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_links', to='api.manualseries')),
            ],
            options={
                'ordering': ['series__code', 'office__name'],
                'constraints': [models.UniqueConstraint(fields=('series', 'office'), name='one_relationship_per_series_and_office')],
            },
        ),
        migrations.RunPython(
            inherit_approval_route_by_default,
            explicit_approval_route,
        ),
    ]
