# Generated by Django 6.0.1 on 2026-09-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_uploaded_by_may_be_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionassignment',
            name='is_acting',
            field=models.BooleanField(default=False),
        ),
    ]
