# Generated by Django 6.0.1 on 2026-09-22 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_acting_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='office',
            field=models.ForeignKey(blank=True, help_text='Leave empty to show this to every office.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='api.office'),
        ),
        migrations.CreateModel(
            name='AccessMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_position', models.BooleanField(default=False)),
                ('switched_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('switched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switchovers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'access mode',
            },
        ),
    ]
