# Generated by Django 6.0.1 on 2026-09-22 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_switchover_and_office_notices'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionpreassessment',
            name='retrieved_section_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('concurrence', 'Out for concurrence'), ('locked', 'Locked'), ('withdrawn', 'Withdrawn')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals_created', to=settings.AUTH_USER_MODEL)),
                ('initiating_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals_initiated', to='api.office')),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='api.manual')),
                ('withdrawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_withdrawn', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('overall_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.proposal')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_versions_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['proposal', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Concurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('concur', 'Concurs'), ('return', 'Returned with feedback')], max_length=16)),
                ('feedback', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concurrences', to='api.office')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concurrences_recorded', to=settings.AUTH_USER_MODEL)),
                ('recorded_by_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concurrences_recorded', to='api.position')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concurrence_feedback', to='api.manualsection')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concurrences', to='api.proposalversion')),
            ],
            options={
                'ordering': ['version', 'office__name'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted for concurrence'), ('concurred', 'Concurred'), ('returned', 'Returned with feedback'), ('redrafted', 'Redrafted'), ('locked', 'Locked'), ('withdrawn', 'Withdrawn')], max_length=16)),
                ('office_name_at_time', models.CharField(blank=True, max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposal_events', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposal_events', to='api.office')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_events', to='api.position')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.proposal')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='api.proposalversion')),
            ],
            options={
                'ordering': ['proposal', 'at'],
            },
        ),
        migrations.CreateModel(
            name='SectionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_text', models.TextField(blank=True)),
                ('new_text', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('section_content_hash', models.CharField(blank=True, max_length=64)),
                ('is_open', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_change', to='api.revisionpreassessment')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_changes', to='api.manualsection')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='api.proposalversion')),
            ],
            options={
                'ordering': ['version', 'section__order'],
            },
        ),
        migrations.CreateModel(
            name='ProposalParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name_at_time', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('concurring', 'Must concur'), ('approving', 'Signs')], max_length=16)),
                ('route_order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposal_participations', to='api.office')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.proposal')),
            ],
            options={
                'ordering': ['proposal', 'role', 'route_order', 'office_name_at_time'],
                'constraints': [models.UniqueConstraint(fields=('proposal', 'office', 'role'), name='one_participation_per_office_and_role')],
            },
        ),
        migrations.AddConstraint(
            model_name='proposalversion',
            constraint=models.UniqueConstraint(fields=('proposal', 'number'), name='one_row_per_proposal_version'),
        ),
        migrations.AddConstraint(
            model_name='concurrence',
            constraint=models.UniqueConstraint(fields=('version', 'office'), name='one_decision_per_office_per_version'),
        ),
        migrations.AddConstraint(
            model_name='sectionchange',
            constraint=models.UniqueConstraint(fields=('version', 'section'), name='one_change_per_section_per_version'),
        ),
        migrations.AddConstraint(
            model_name='sectionchange',
            constraint=models.UniqueConstraint(condition=models.Q(('is_open', True)), fields=('section',), name='one_open_change_per_section'),
        ),
    ]
