# Generated by Django 6.0.1 on 2026-09-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_proposals'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('object_id', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('created', 'Created by the seeder'), ('changed', 'Existing row the seeder modified')], max_length=16)),
                ('previous', models.JSONField(blank=True, default=dict)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
