# Generated by Django 6.1 on 2026-09-23 07:24

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_demo_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('dcr_generated', 'Document Change Request (generated)'), ('pages_generated', 'Draft copy of the document (generated)'), ('concurrence_record', 'Record of concurrence (generated)'), ('signed_dcr', 'Signed Document Change Request'), ('signed_pages', 'Signed draft copy')], max_length=32)),
                ('slot', models.CharField(blank=True, max_length=32)),
                ('file', models.FileField(upload_to=api.models.attachment_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('replacement_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['proposal', 'kind', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='proposal',
            name='dcr_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='event',
            field=models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted for concurrence'), ('concurred', 'Concurred'), ('returned', 'Returned with feedback'), ('redrafted', 'Redrafted'), ('locked', 'Locked'), ('documents_generated', 'Documents generated'), ('scan_uploaded', 'Signed copy uploaded'), ('scan_replaced', 'Signed copy replaced'), ('withdrawn', 'Withdrawn')], max_length=32),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('concurrence', 'Out for concurrence'), ('locked', 'Locked'), ('awaiting_signature', 'Awaiting signature'), ('ready_for_imr', 'Ready for the IMR'), ('withdrawn', 'Withdrawn')], default='draft', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.UniqueConstraint(condition=models.Q(('dcr_number', ''), _negated=True), fields=('dcr_number',), name='one_proposal_per_dcr_number'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.proposal'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='api.manualsection'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='api.attachment'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.proposalversion'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.UniqueConstraint(condition=models.Q(('superseded_at__isnull', True)), fields=('version', 'kind', 'slot'), name='one_current_attachment_per_slot'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.UniqueConstraint(condition=models.Q(('supersedes__isnull', False)), fields=('supersedes',), name='one_replacement_per_attachment'),
        ),
    ]
