# Generated by Django 6.1 on 2026-09-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_attachments_and_dcr_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='created_as',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='event',
            field=models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted for concurrence'), ('concurred', 'Concurred'), ('returned', 'Returned with feedback'), ('redrafted', 'Redrafted'), ('locked', 'Locked'), ('documents_generated', 'Documents generated'), ('scan_uploaded', 'Signed copy uploaded'), ('scan_replaced', 'Signed copy replaced'), ('package_complete', 'Signed copies complete'), ('withdrawn', 'Withdrawn')], max_length=32),
        ),
    ]
