# Generated by Django 6.1 on 2026-09-23 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


FROZEN = ('locked', 'awaiting_signature', 'ready_for_imr')


def hold_frozen_sections(apps, schema_editor):
    """Frozen requests hold their sections from now on; restore the holds.

    Until this migration a request let go of its sections at the lock. A
    request already locked must now hold them again - unless another
    request has claimed one of those sections since, in which case taking
    it back would break the one-hold-per-section index. That case is left
    unheld and printed, not hidden: someone has to decide between the two.
    """
    Proposal = apps.get_model('api', 'Proposal')
    SectionChange = apps.get_model('api', 'SectionChange')
    for proposal in Proposal.objects.filter(status__in=FROZEN):
        current = proposal.versions.order_by('-number').first()
        if current is None:
            continue
        for change in SectionChange.objects.filter(version=current, is_open=False):
            if SectionChange.objects.filter(section_id=change.section_id, is_open=True).exists():
                print(f"\n  NOT HELD: section {change.section_id} of proposal {proposal.id} "
                      f"is already held by another proposal.")
                continue
            SectionChange.objects.filter(pk=change.pk).update(is_open=True)


def release_frozen_sections(apps, schema_editor):
    Proposal = apps.get_model('api', 'Proposal')
    SectionChange = apps.get_model('api', 'SectionChange')
    SectionChange.objects.filter(
        version__proposal__status__in=FROZEN, is_open=True,
    ).update(is_open=False)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_signed_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionhistory',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_versions', to='api.proposal'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='kind',
            field=models.CharField(choices=[('dcr_generated', 'Document Change Request (generated)'), ('pages_generated', 'Draft copy of the document (generated)'), ('concurrence_record', 'Record of concurrence (generated)'), ('signed_dcr', 'Signed Document Change Request'), ('signed_pages', 'Signed draft copy'), ('approved_dcr', 'DCR signed by the approving authority')], max_length=32),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='event',
            field=models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted for concurrence'), ('concurred', 'Concurred'), ('returned', 'Returned with feedback'), ('redrafted', 'Redrafted'), ('locked', 'Locked'), ('documents_generated', 'Documents generated'), ('scan_uploaded', 'Signed copy uploaded'), ('scan_replaced', 'Signed copy replaced'), ('package_complete', 'Signed copies complete'), ('imr_accepted', 'Accepted by the IMR'), ('imr_denied', 'Denied by the IMR'), ('approval_uploaded', 'Approving authority signed'), ('package_returned', 'Returned for package defects'), ('made_effective', 'Made effective'), ('withdrawn', 'Withdrawn')], max_length=32),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('concurrence', 'Out for concurrence'), ('locked', 'Locked'), ('awaiting_signature', 'Awaiting signature'), ('ready_for_imr', 'Ready for the IMR'), ('denied', 'Denied by the IMR'), ('awaiting_approval', 'Awaiting the approving authority'), ('with_custodian', 'With the Document Custodian'), ('package_returned', 'Returned for package defects'), ('effective', 'Effective'), ('withdrawn', 'Withdrawn')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='sectionhistory',
            name='source',
            field=models.CharField(choices=[('revision', 'Approved revision'), ('proposal', 'Change request made effective'), ('direct', 'Direct edit by an admin'), ('merge', 'Merged with another section'), ('extraction', 'Re-extracted from the master copy'), ('unknown', 'Recorded before edits were attributed')], default='unknown', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=32)),
                ('revision', models.CharField(max_length=32)),
                ('effective_on', models.DateField()),
                ('updated_in_ids_on', models.DateField(blank=True, null=True)),
                ('recorded_as', models.CharField(max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='api.manual')),
                ('proposal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_status', to='api.proposal')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'document statuses',
                'ordering': ['manual', 'recorded_at'],
            },
        ),
        migrations.AddField(
            model_name='manual',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.documentstatus'),
        ),
        migrations.AddField(
            model_name='manualsection',
            name='status_changed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections_changed', to='api.documentstatus'),
        ),
        migrations.CreateModel(
            name='QmsDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('imr', 'IMR'), ('custodian', 'Document Custodian')], max_length=16)),
                ('outcome', models.CharField(choices=[('accept', 'Accepted'), ('deny', 'Denied'), ('return', 'Returned for package defects'), ('effective', 'Made effective')], max_length=16)),
                ('comments', models.TextField(blank=True)),
                ('returned_kinds', models.JSONField(blank=True, default=list)),
                ('decided_as', models.CharField(max_length=255)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qms_decisions', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qms_decisions', to='api.proposal')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qms_decisions', to='api.proposalversion')),
            ],
            options={
                'ordering': ['proposal', 'decided_at'],
            },
        ),
        migrations.RunPython(hold_frozen_sections, release_frozen_sections),
    ]
