# Generated by Django 6.1 on 2026-09-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_qms_decisions_and_document_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'concurrence'])), fields=('manual', 'initiating_office'), name='one_open_proposal_per_office_and_document'),
        ),
    ]
