# Generated by Django 6.1 on 2026-09-24 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_one_open_proposal_per_office_and_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentstatus',
            name='correction_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentstatus',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentstatus',
            name='superseded_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supersedes', to='api.documentstatus'),
        ),
    ]
