# Generated by Django 6.1 on 2026-09-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_retire_departments_and_the_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalversion',
            name='proposal_note',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='revisionpreassessment',
            name='note_choices',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
