# Generated by Django 6.1 on 2026-10-05 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=32, unique=True)),
                ('generated_as', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('status_at_time', models.CharField(max_length=32)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trail_reports', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trail_reports', to='api.proposal')),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
            },
        ),
    ]
