# Generated by Django 6.1 on 2026-10-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_trail_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionhistory',
            name='source',
            field=models.CharField(choices=[('proposal', 'Change request made effective'), ('direct', 'Direct edit by an admin'), ('extraction', 'Re-extracted from the master copy'), ('structure', 'Extraction corrected (merged or split)'), ('unknown', 'Recorded before edits were attributed')], default='unknown', max_length=20),
        ),
    ]
