# Generated by Django 6.1 on 2026-10-05 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_history_structure_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='requested_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='api.office'),
        ),
    ]
