"""Generate manual_vocabulary.txt: the manuals' own words the dictionary lacks.

The unknown_word advisory (advisory_checks.py) accepts a word if it is in the
English dictionary or in this file. Committed rather than read from the
database at check time, so Layer 1 stays deterministic and independent of
whatever the database holds - the same reason entities.json is a file.

Only lower-case words are collected, as only those are checked. Words known
to be extraction or typing errors are left out (EXCLUDE below), so a new edit
that repeats one is still caught. Review the diff before committing.

    ../venv/Scripts/python.exe ml/revision_pipeline/scripts/build_manual_vocabulary.py \\
        --db <a COPY of db.sqlite3>

Re-run it when manuals are added, then review and commit the file.
"""

from __future__ import annotations

import argparse
import sqlite3
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve()
sys.path.insert(0, str(HERE.parents[2]))

from revision_pipeline.advisory_checks import VOCABULARY_FILE, _checkable_words, _speller  # noqa: E402

# Reviewed 2026-09-30: words in the manuals that are errors, not vocabulary.
EXCLUDE = {
    "ifany",        # "if any", run together by extraction
    "srecords",     # "'s records"
    "witnessesin",  # "witnesses in"
}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--db", required=True, help="a COPY of db.sqlite3")
    args = ap.parse_args()

    speller = _speller()
    if speller is None:
        raise SystemExit("pyspellchecker is not installed: pip install -r requirements.txt")

    db = sqlite3.connect(f"file:{args.db}?mode=ro", uri=True)
    counts, manuals = Counter(), set()
    for title, content in db.execute(
            "select m.title, s.content from api_manualsection s "
            "join api_manual m on m.id = s.manual_id"):
        manuals.add(title)
        counts.update(_checkable_words(content or ""))

    unknown = sorted(speller.unknown(list(counts)))
    kept = [w for w in unknown if w not in EXCLUDE]
    header = [
        "# The manuals' own words that the English dictionary lacks.",
        "# Generated by scripts/build_manual_vocabulary.py from "
        f"{len(manuals)} manuals; reviewed before committing.",
        "# The unknown_word advisory accepts these. Excluded as errors: "
        + ", ".join(sorted(EXCLUDE)) + ".",
    ]
    VOCABULARY_FILE.write_text("\n".join(header + kept) + "\n", encoding="utf-8", newline="\n")
    print(f"{len(kept)} words from {len(manuals)} manuals -> {VOCABULARY_FILE.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
